// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdzybtmlaikpiteqnaiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkenlidG1sYWlrcGl0ZXFuYWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMzc5ODgsImV4cCI6MjA3MDcxMzk4OH0.eGOH5FSl_1kEjpK0CybCOsunk9VdAg7lsc8cCOkHtlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});